name = "Hexwoven"
author = "Weavers of Hexes"
version = "6.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49fec9b6c56bb2dec87396bb259c9b2519735e738abc240b971f846fa9562907"

[versions]
fabric = "0.19.5"
minecraft = "1.20.1"
