name = "Hexwoven"
author = "Weavers of Hexes"
version = "6.1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50afaf09a14f45b4f4e91fa6229f2b294a0159949b4a88b909f524ac43e0f37e"

[versions]
fabric = "0.19.5"
minecraft = "1.20.1"
