name = "Hexwoven"
author = "Weavers of Hexes"
version = "6.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "034c2b5d1879f25792d5c8a2766760c57243eff74a74fe72e4134da6cd6a75c2"

[versions]
fabric = "0.19.5"
minecraft = "1.20.1"
